import type { Article, Author, Category } from "@/types/news";

const image = (id: string, width = 1400) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
export const authors: Author[] = [
  { slug: "ananya-rao", name: "Ananya Rao", role: "National Editor", bio: "Ananya writes about India’s changing cities, public institutions and the choices shaping everyday life.", expertise: ["Urban India", "Public policy", "Climate"], avatar: image("photo-1494790108377-be9c29b29330", 160), social: { x: "#" } },
  { slug: "rohan-mehta", name: "Rohan Mehta", role: "Technology Correspondent", bio: "Rohan covers the companies, builders and ideas behind India’s digital economy.", expertise: ["Technology", "AI", "Startups"], avatar: image("photo-1500648767791-00dcc994a43e", 160), social: { x: "#", linkedin: "#" } },
  { slug: "nisha-verma", name: "Nisha Verma", role: "Climate Reporter", bio: "Nisha reports on climate science and its human consequences across South Asia.", expertise: ["Climate", "Science", "Environment"], avatar: image("photo-1534528741775-53994a69daeb", 160) }
];
export const categories: Category[] = [
  { id: "india", slug: "india", name: "India", title: "India", description: "The people, policies and places changing the country.", image: image("photo-1592639296346-560c37a0f711") },
  { id: "technology", slug: "technology", name: "Technology", title: "Technology", description: "India’s digital economy, explained with clarity.", image: image("photo-1516321318423-f06f85e504b3") },
  { id: "business", slug: "business", name: "Business", title: "Business", description: "Markets, companies and the ideas moving money.", image: image("photo-1611974789855-9c2a0a7236a3") },
  { id: "world", slug: "world", name: "World", title: "World", description: "Context for the events beyond our borders.", image: image("photo-1521295121783-8a321d551ad2") }
];
export const articles: Article[] = [
  { id: "1", slug: "a-new-rhythm-for-indias-cities", category: "India", title: "A new rhythm for India’s cities is quietly taking shape", excerpt: "From smarter public spaces to cooler streets, urban India is designing for a more livable future.", image: image("photo-1592639296346-560c37a0f711"), author: "Ananya Rao", authorSlug: "ananya-rao", publishedAt: "August 1, 2026", updatedAt: "August 1, 2026, 10:42 AM IST", readTime: "6 min read", views: "18.4K", caption: "The city is increasingly being designed around the people who move through it.", tags: ["Urban India", "Climate", "Public Policy"], content: [{ type: "paragraph", value: "Across India, a subtle recalibration is under way. City planners, community groups and residents are beginning to ask a more useful question: what makes a neighbourhood work well on an ordinary Tuesday?" }, { type: "heading", value: "A more human measure of growth" }, { type: "paragraph", value: "The answer is rarely a single large project. It is shade at a bus stop, a safer crossing, a park that stays open after sunset, and public systems that respect people’s time." }, { type: "quote", value: "The best city interventions are often the ones that make daily life feel a little less difficult." }, { type: "paragraph", value: "That approach is also changing how success is measured: not just by new infrastructure, but by whether more people can use a city comfortably and safely." }] },
  { id: "2", slug: "indias-next-software-story", category: "Technology", title: "India’s next software story is being written beyond the big cities", image: image("photo-1521737711867-e3b97375f902"), author: "Rohan Mehta", authorSlug: "rohan-mehta", publishedAt: "August 1, 2026", readTime: "4 min read", tags: ["Startups", "Technology", "AI"] },
  { id: "3", slug: "the-monsoons-message", category: "Climate", title: "The monsoon’s message is clearer than ever", image: image("photo-1534274988757-a28bf1a57c17"), author: "Nisha Verma", authorSlug: "nisha-verma", publishedAt: "August 1, 2026", readTime: "5 min read", tags: ["Climate", "Monsoon"] },
  { id: "4", slug: "markets-find-their-footing", category: "Business", title: "Markets find their footing as investors look to the long view", image: image("photo-1611974789855-9c2a0a7236a3"), author: "Kabir Shah", publishedAt: "August 1, 2026", readTime: "3 min read", tags: ["Markets", "Economy"] },
  { id: "5", slug: "shared-screen-magic", category: "Culture", title: "The small theatres bringing back the magic of a shared screen", image: image("photo-1489599849927-2ee91cede3ba"), author: "Maya Sen", publishedAt: "July 31, 2026", readTime: "7 min read", tags: ["Culture", "Cinema"] },
  { id: "6", slug: "healthier-india-street-level", category: "Health", title: "What a healthier India could look like at street level", image: image("photo-1505751172876-fa1923c5c528"), author: "Sana Khan", publishedAt: "July 31, 2026", readTime: "4 min read", tags: ["Health", "Public Health"] },
  { id: "7", slug: "new-language-of-winning", category: "Sports", title: "A generation of athletes is changing the language of winning", image: image("photo-1461896836934-ffe607ba8211"), author: "Dev Malhotra", publishedAt: "July 30, 2026", readTime: "5 min read", tags: ["Sports", "Athletes"] }
];
