"use client";
import { AnimatePresence, motion } from "framer-motion";
import { AlertCircle, ChevronDown, LoaderCircle, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/primitives";

export function Modal({ open, onClose, title, children }: React.PropsWithChildren<{ open: boolean; onClose: () => void; title: string }>) { useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); addEventListener("keydown", close); return () => removeEventListener("keydown", close); }, [onClose]); return <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={title} onMouseDown={onClose}><motion.div initial={{ y: 15, scale: .98 }} animate={{ y: 0, scale: 1 }} className="w-full max-w-lg rounded-2xl bg-paper p-6 shadow-2xl" onMouseDown={event => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="editorial text-2xl font-bold">{title}</h2><button onClick={onClose} aria-label="Close dialog" className="rounded-lg p-2 hover:bg-soft"><X size={18}/></button></div>{children}</motion.div></motion.div>}</AnimatePresence>; }
export function Drawer({ open, onClose, children }: React.PropsWithChildren<{ open: boolean; onClose: () => void }>) { return <AnimatePresence>{open && <><motion.button aria-label="Close drawer" className="fixed inset-0 z-40 bg-ink/30" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}/><motion.aside initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", damping: 28, stiffness: 260 }} className="fixed right-0 top-0 z-50 h-full w-full max-w-sm bg-paper p-6 shadow-2xl">{children}</motion.aside></>}</AnimatePresence>; }
export function Accordion({ items }: { items: Array<{ title: string; content: string }> }) { const [active, setActive] = useState<number | null>(null); return <div className="divide-y border-y">{items.map((item, index) => <div key={item.title}><button className="flex w-full items-center justify-between py-4 text-left text-sm font-bold" onClick={() => setActive(active === index ? null : index)} aria-expanded={active === index}>{item.title}<ChevronDown className={cn("transition", active === index && "rotate-180")} size={17}/></button><AnimatePresence>{active === index && <motion.p initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden pb-4 text-sm leading-6 text-muted">{item.content}</motion.p>}</AnimatePresence></div>)}</div>; }
export function Tabs({ tabs }: { tabs: string[] }) { const [active, setActive] = useState(tabs[0]); return <div role="tablist" className="flex gap-1 overflow-x-auto border-b">{tabs.map(tab => <button key={tab} role="tab" aria-selected={active === tab} onClick={() => setActive(tab)} className={cn("shrink-0 border-b-2 px-3 py-2 text-xs font-bold", active === tab ? "border-signal text-signal" : "border-transparent text-muted")}>{tab}</button>)}</div>; }
export function Pagination({ current = 1, total = 5 }: { current?: number; total?: number }) { return <nav aria-label="Pagination" className="flex gap-1">{Array.from({ length: total }, (_, i) => <button key={i} aria-current={current === i + 1 ? "page" : undefined} className={cn("grid h-8 w-8 place-items-center rounded-lg text-xs font-bold", current === i + 1 ? "bg-ink text-white" : "hover:bg-soft")}>{i + 1}</button>)}</nav>; }
export function Carousel({ children }: { children: React.ReactNode[] }) { const [active, setActive] = useState(0); const track = useRef<HTMLDivElement>(null); const move = (next: number) => { setActive(next); track.current?.children[next]?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "start" }); }; return <div className="overflow-hidden"><div ref={track} className="flex snap-x snap-mandatory overflow-x-hidden scroll-smooth">{children.map((child, index) => <div className="w-full shrink-0 snap-start" key={index}>{child}</div>)}</div><div className="mt-4 flex items-center justify-between"><Button variant="ghost" size="sm" onClick={() => move(Math.max(0, active - 1))} disabled={active === 0}>Previous</Button><p className="text-xs font-bold text-muted">{active + 1} / {children.length}</p><Button variant="ghost" size="sm" onClick={() => move(Math.min(children.length - 1, active + 1))} disabled={active === children.length - 1}>Next</Button></div></div>; }
export function Toast({ message, open, onClose }: { message: string; open: boolean; onClose: () => void }) { useEffect(() => { if (!open) return; const timer = setTimeout(onClose, 4000); return () => clearTimeout(timer); }, [open, onClose]); return <AnimatePresence>{open && <motion.div role="status" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }} className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white shadow-2xl">{message}</motion.div>}</AnimatePresence>; }
export function Skeleton({ className }: { className?: string }) { return <div className={cn("animate-pulse rounded-lg bg-slate-200", className)}/>; }
export function LoadingSpinner() { return <LoaderCircle aria-label="Loading" className="animate-spin text-signal"/>; }
export function EmptyState({ title = "Nothing here yet", description = "New stories will appear here soon." }: { title?: string; description?: string }) { return <div className="rounded-xl border border-dashed p-8 text-center"><p className="font-bold">{title}</p><p className="mt-1 text-sm text-muted">{description}</p></div>; }
export function ErrorState({ title = "Something went wrong" }: { title?: string }) { return <div role="alert" className="flex gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900"><AlertCircle className="shrink-0 text-signal" size={19}/><div><p className="font-bold">{title}</p><p className="mt-1">Please refresh the page or try again later.</p></div></div>; }
