"use client";
import { ChevronDown, Search, X } from "lucide-react";
import { useState } from "react";
import Image from "next/image";
import { cn } from "@/lib/utils";

type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost"; size?: "sm" | "md" | "lg" };
export function Button({ className, variant = "primary", size = "md", ...props }: ButtonProps) { return <button className={cn("inline-flex items-center justify-center rounded-lg font-bold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-signal disabled:opacity-50", variant === "primary" && "bg-signal text-white hover:bg-red-800", variant === "secondary" && "bg-ink text-paper hover:opacity-90", variant === "ghost" && "hover:bg-soft", size === "sm" && "px-3 py-2 text-xs", size === "md" && "px-4 py-2.5 text-sm", size === "lg" && "px-5 py-3 text-base", className)} {...props} />; }
export function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("w-full rounded-lg border bg-paper px-3 py-2.5 text-sm outline-none transition placeholder:text-muted focus:border-signal focus:ring-2 focus:ring-signal/15", className)} {...props} />; }
export function Textarea({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("min-h-28 w-full rounded-lg border bg-paper px-3 py-2.5 text-sm outline-none focus:border-signal focus:ring-2 focus:ring-signal/15", className)} {...props} />; }
export function Badge({ children, className }: React.PropsWithChildren<{ className?: string }>) { return <span className={cn("inline-flex rounded-full bg-red-50 px-2.5 py-1 text-[10px] font-extrabold tracking-wider text-signal", className)}>{children}</span>; }
export function Chip({ children, active = false, onClick }: React.PropsWithChildren<{ active?: boolean; onClick?: () => void }>) { return <button onClick={onClick} className={cn("rounded-full border px-3 py-1.5 text-xs font-semibold transition hover:border-signal hover:text-signal", active && "border-signal bg-signal text-white hover:text-white")}>{children}</button>; }
export function Avatar({ name, src, size = "md" }: { name: string; src?: string; size?: "sm" | "md" | "lg" }) { const dimensions = size === "sm" ? "h-7 w-7 text-[10px]" : size === "lg" ? "h-12 w-12 text-sm" : "h-9 w-9 text-xs"; return src ? <Image className={cn("rounded-full object-cover", dimensions)} src={src} alt="" width={48} height={48}/> : <span aria-label={name} className={cn("grid rounded-full bg-ink font-bold text-white place-items-center", dimensions)}>{name.split(" ").map(word => word[0]).join("")}</span>; }
export function Tooltip({ label, children }: React.PropsWithChildren<{ label: string }>) { return <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 mb-2 -translate-x-1/2 whitespace-nowrap rounded bg-ink px-2 py-1 text-[10px] text-white opacity-0 transition group-hover:opacity-100">{label}</span></span>; }
export function SearchBox({ onClose, defaultValue }: { onClose?: () => void; defaultValue?: string }) { return <div className="flex items-center gap-2 rounded-xl border bg-paper px-3 py-2 shadow-sm"><Search size={18} className="text-signal"/><Input name="q" defaultValue={defaultValue} aria-label="Search DailySamachar" placeholder="Search stories, topics and people" className="border-0 bg-transparent p-0 shadow-none focus:ring-0"/>{onClose && <Button variant="ghost" size="sm" aria-label="Close search" onClick={onClose}><X size={17}/></Button>}</div>; }
export function Dropdown({ label, items }: { label: string; items: string[] }) { const [open, setOpen] = useState(false); return <div className="relative"><Button variant="ghost" size="sm" onClick={() => setOpen(!open)} aria-expanded={open}>{label}<ChevronDown size={14} className="ml-1"/></Button>{open && <div className="absolute right-0 top-full z-40 mt-2 w-44 rounded-xl border bg-paper p-1 shadow-xl">{items.map(item => <a className="block rounded-lg px-3 py-2 text-sm hover:bg-soft" href="#dropdown" key={item}>{item}</a>)}</div>}</div>; }
